### ISSUE TITLE
Getting error --> Unable to Use Amazon Authorization Manager. APIKey is incorrect or does not exist. Does assets/api_key.txt exist in the main application?

### ISSUE THREAD

**Issue by TheOrangeTester** [willblaschko/AlexaAndroid#5] opened 2016-05-26 07:12 UTC
When I tried to run sample application I am getting above error.

I have already added api_key.txt in asset folder still I am getting this error.

Do we need to run application in release mode ?

**Comment by vw2k3** [comment] 2016-05-26 08:08
I think it might be package name not matching API Key's package name.
Try this,
In Android Studio Right click 'app'>Open Module Settings>Flavors
The "Application Id"  should be match 
[Amazon Developer Console](https://developer.amazon.com/)>Alexa>Alexa Voice Service>Your Registered Products>Security Profile>Android/Kindle Settings>Package

**Comment by willblaschko** [comment] 2016-05-26 15:19
@vw2k3 's solution is probably correct. Make sure you've changed the package name from the default and that you're using the same key to sign the application as you defined in your security profile.

Because the default package name is already registered to my key, it likely won't work until you change the package name (most easily done in the build.gradle file).

**Comment by TheOrangeTester** [comment] 2016-05-27 05:24
Thank you Guys!! Issue resolved!!!

**Comment by TheOrangeTester** [comment] 2016-05-27 09:33
Hey Guys,
Sorry for troubling you again.

When I try to run the sample I am getting error from Amazon when I accepted the security profile term & condition.

error : 
"We're sorry An error occurred when we tried to process your request. Rest assured we're already working on this problem....."

Am I missing something or Its is issue with Amazon ?

An Indicator appearing on window which keeps rotating.

**Comment by willblaschko** [comment] 2016-05-27 14:39
That sounds like an Amazon issue I haven't encountered before. Is it still happening?

**Comment by willblaschko** [comment] 2016-05-27 14:40
If it's still happening, make it a new issue so we can close this one :)

**Closed** 2016-05-28 10:55 UTC

**Comment by prasannakumark** [comment] 2017-11-14 13:10
Hi All,

Still I am facing this issue, cloud  you please tell me any root cause for this problem

In Android Studio Right click 'app'>Open Module Settings>Flavors
The "Application Id" should be match
**com.willblaschko.android.test**

Amazon package name

**com.willblaschko.android.test**

**Comment by tonyw05** [comment] 2018-08-06 17:23
@willblaschko 
I am currently facing the error of missing my api_key.  It is in the correct spot and I have set it up correctly, but when you say "Make sure you've changed the package name from the default and that you're using the same key to sign the application as you defined in your security profile. Because the default package name is already registered to my key, it likely won't work until you change the package name (most easily done in the build.gradle file)." does that mean I have to change all instances of com.willblaschko.android.alexavoicelibrary in my code to something else even if I have it matched to amazon correctly. If so what am I able to change it to?
